Fix config template's consumption of unicode dictionaries
The yaml safe_dump method cannot handle a merged dict containing both
unicode and non-unicode values.

I9159be497c201ca6c2f558336843be5175f0ee2c was not able to be backported
as it requires ansible 2.2, which is not guaranteed for newton.

The merged_resultant being `{u'foo': u'bar', 'baz': True}` causes the
following error.
RepresenterError: cannot represent an object: foo

Change-Id: I8986688efbd7e05ba17c3d61ee032dcc29d3b05d